### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by enricodeleo** [Altaba77/ngx-walkthrough#1]
First of all: thank you for your work. I was searching for just such a library.

I gave a shot (installed from npm) but I got an error as unrecognized character, maybe there is some compiling issue. Furthermore, an improved readme would be great!

**Comment by Altaba77** [comment]
Hello,

I am testing the library with different version of angular and currently only angular 5 and above is working, so I updated the readme. I will try to fix this problem because I want the library work with angular >2.

You can still copy paste the component (and the asset for the icons) in your project if you want to use it right now it should work (you may have to change the path for the icons).

Can you be more specific about what could be improved in the readme ?

**Comment by enricodeleo** [comment]
Thank you for your reply. Yes I am under Angular 5.

I would add some more example and a couple of lines about how to import the module.

**Comment by Altaba77** [comment]
I updated the compilation process it should work with angular 5 I will test with other version of angular and with Ionic 3 this WE if I found time...
Futhermore I updated the readme, I hope it is clearer now.

**Comment by mbonig** [comment]
I'm having the same problem with the following package:

```
    "@angular-redux/store": "^7.1.1",
    "@angular/common": "5.2.8",
    "@angular/compiler": "5.2.8",
    "@angular/compiler-cli": "5.2.8",
    "@angular/core": "5.2.8",
    "@angular/forms": "5.2.8",
    "@angular/http": "5.2.8",
    "@angular/platform-browser": "5.2.8",
    "@angular/platform-browser-dynamic": "5.2.8",
    "@angular/platform-server": "5.2.8",
    "@ionic-native/core": "^4.5.3",
    "@ionic-native/geolocation": "^4.5.3",
    "@ionic-native/splash-screen": "4.5.3",
    "@ionic-native/status-bar": "^4.5.3",
    "@ionic/storage": "2.1.3",
    "angular2-moment": "^1.2.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "ngx-pipes": "^2.1.2",
    "ngx-walkthrough": "^0.1.16",
    "qs": "^6.3.0",
    "redux": "^3.6.0",
    "rxjs": "5.5.6",
    "socket.io-client": "^2.0.4",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.20"
```
This is the specific error:

![image](https://user-images.githubusercontent.com/1559437/37259385-23657840-254b-11e8-8a7e-644da4e68065.png)


Could this be caused by something else?

**Comment by Altaba77** [comment]
Hello,

I did a full refactoring of the library and I fixed this error. 
I did few tests with Angular 5 and Ionic 4, everything seems to work properly now.

**Comment by DoryZi** [comment]
@Altaba77 Hey mate, I would like to fork and add things to this, can you help me build? (see my other issue)..

**Comment by SonuSahoo** [comment]
> Thank you for your reply. Yes I am under Angular 5.
> 
> I would add some more example and a couple of lines about how to import the module.

Hi
Can you tell me how can i use it  homepage after login.
