### ISSUE TITLE
Cannot find module '@angular/core/src/metadata/lifecycle_hooks' in Angular 8.

### ISSUE THREAD

**Issue by antoinedelia** [Altaba77/ngx-walkthrough#10]
Hi,

I've just installed this package in my Angular 8 application, and I got the following error:

`ERROR in node_modules/ngx-walkthrough/components/walkthrough.component/walkthrough.component.d.ts(2,81): error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'`

To get rid of the error, I had to make the following changes.

**Before:**
`import { AfterViewChecked, OnChanges, SimpleChanges, AfterContentChecked } from '@angular/core/src/metadata/lifecycle_hooks';` 

**After:**
`import { AfterViewChecked, OnChanges, SimpleChanges, AfterContentChecked } from '@angular/core';`

Could you update the package to get rid of the error please?

Thanks!

**Comment by antoinedelia** [comment]
I created a pull request that should fix the error

**Comment by Altaba77** [comment]
Hello,

I merged the correction, thx for your help.

I also released a new version with the correctif -> 0.3.1.
