### ISSUE TITLE
Ionic 4 lazy loading

### ISSUE THREAD

**Issue by amirgh70** [Altaba77/ngx-walkthrough#12]
Hello
I want to know is this module working on Ionic 4 lazy loading project? If the answer is yes I would be thankful to know how?
Because I tried this link [https://www.npmjs.com/package/ngx-walkthrough](url) and it's instructions, but I get this error:

> ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

I really do not know what I should do and I would be grateful if you could help me with this problem.
Thanks in advance
Amir

**Comment by Altaba77** [comment]
Hello,
I never tried the lazy loading with ionic 4.
I will test this when I will find some time. 
For start you could try to import common module in your module file in addition of the library.

**Comment by amirgh70** [comment]
Thanks bro.

**Comment by khaukheng** [comment]
Have the same issue with ionic 4 with angular 6 that use lazy loading, adding CommonModule to the lazy loaded module does not help.

**Comment by Altaba77** [comment]
Hello,

I fixed the imports, that should solve the problem.

**Comment by khaukheng** [comment]
Thank you for the prompt response, I'll try again afterward. ☺️

**Comment by khaukheng** [comment]
It's working.
