### ISSUE TITLE
Correct way to add multiple steps in a walkthrough? 

### ISSUE THREAD

**Issue by TommiSvard** [Altaba77/ngx-walkthrough#13]
Thank you for a useful library!

I about the best way to implement multiple steps in a walkthrough? I have a solution here: https://stackblitz.com/edit/angular-sjzqdv . But i dont know if that is a intended solution or if there's an easier way of doing it?

**Comment by Altaba77** [comment]
Hello,

it is the intended solution, you can also use different components and use the two output (show and hide) to switch between them.
