### ISSUE TITLE
'walkthrough' is not a known element:

### ISSUE THREAD

**Issue by bobo04020802** [Altaba77/ngx-walkthrough#5]
use walkthrough in ionic 3.9.2 angular 5.2.10  for app , step to step use you wiki, but error **'walkthrough' is not a known element.**

please help me!! 

package.json
    "angular/animations": "5.2.10",
    "angular/common": "5.2.10",
    "angular/compiler": "5.2.10",
    "angular/compiler-cli": "5.2.10",
    "angular/core": "5.2.10",
    "angular/forms": "5.2.10",
    "angular/http": "5.2.10",
    "angular/platform-browser": "5.2.10",
    "angular/platform-browser-dynamic": "5.2.10",
    "ionic-native/camera": "4.3.3",
    "ionic-native/core": "4.7.0",
    "ionic-native/device": "^4.7.0",
    "ionic-native/file": "^4.7.0",
    "ionic-native/file-opener": "^4.7.0",
    "ionic-native/file-transfer": "^4.7.0",
    "ionic-native/network": "^4.7.0",
    "ionic-native/screen-orientation": "^4.7.0",
    "ionic-native/splash-screen": "4.7.0",
    "ionic-native/status-bar": "^4.7.0",
    "ionic-native/streaming-media": "^4.7.0",
    "ionic-native/transfer": "^3.14.0",
    "ionic/storage": "2.1.3",
    "ngx-translate/core": "8.0.0",
    "ngx-translate/http-loader": "^2.0.0",
    "types/echarts": "0.0.13",
    "angular2-jwt": "^0.2.3",
    "cordova-android": "^6.3.0",
    "cordova-plugin-jcore": "^1.1.12",
    "echarts": "^4.1.0",
    "intersection-observer": "^0.5.0",
    "ion2-calendar": "^2.1.7",
    "ionic-angular": "3.9.2",
    "ionic3-jpush": "^1.2.0",
    "ionicons": "3.0.0",
    "jpush-phonegap-plugin": "^3.3.2",
    "jshashes": "^1.0.7",
    "ngx-address": "^1.0.4",
    "ngx-masonry": "^1.1.2",
    "ngx-walkthrough": "^0.2.0",
    "pouchdb": "^6.4.3",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "videogular2": "^6.0.0",
    "zone.js": "0.8.26"

app.module.ts

imports: [
    BrowserModule,WalkthroughModule]

**Comment by Altaba77** [comment]
I will check with this version of Ionic asap

**Comment by Altaba77** [comment]
I did few tests and everything is working with ionic 3.9.2 and angular 5.2.10. Can you copy the error stack ? what did you write in your html page ?

**Comment by bobo04020802** [comment]
<div [ngSwitch]="selectstyle" >
    <div *ngSwitchCase="'shuangshu'">
      <div id="powermap" #powermap></div>
      <div >
        <walkthrough>

        </walkthrough>
      <ion-list class="md-mailbox" >
        <ion-item *ngFor="let item of annexs" class="mbsc-lv-item">
          <div class="md-mail-icon"  tappable (click)="info(item)" [style.background]="item.color">{{item.name[0]}}</div>
          
          <div class="md-mail-from" tappable (click)="info(item)">{{item.name}}</div>
          <div class="md-mail-subject"  tappable (click)="info(item)" innerHTML="{{item.des?item.des:'描述空空如也……'}}"></div>
          <button ion-button icon-left [style.color]="item.color" clear item-end (click)="moveMarker(item.latlng)">
            <ion-icon name="navigate"></ion-icon>
            位置
          </button>
        </ion-item>
      </ion-list>
      </div>
i use lazy load, evening as you wiki setting , so  i don't known why error .can you send you test to github .

thanks you~~

**Comment by bobo04020802** [comment]
`ERROR Error: Uncaught (in promise): Error: Template parse errors:
'walkthrough' is not a known element:
1. If 'walkthrough' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  </ion-refresher>
  <ion-title class="cheadertitle" #title >Walk</ion-title>
  [ERROR ->]<walkthrough>

  </walkthrough>
"): ng:///HomePageModule/HomePage.html@88:2
Error: Template parse errors:
'walkthrough' is not a known element:
1. If 'walkthrough' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  </ion-refresher>
  <ion-title class="cheadertitle" #title >Walk</ion-title>
  [ERROR ->]<walkthrough>

  </walkthrough>
"): ng:///HomePageModule/HomePage.html@88:2`


error is here, i feel some setting error,  or dependencies of  package.json Less dependence？

**Comment by bobo04020802** [comment]
```
"compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "src/**/*.spec.ts",
    "src/**/__tests__/*.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
```
this is tsconfig.json setting

**Comment by Altaba77** [comment]
The module cannot work if you do not add attributes in the module.
example: 
<walkthrough
            [is-round]="true"
            [walkthrough-type]="'transparency'"
            [focus-element-selector]="'#focusItem'"
            [icon]="'single_tap'"
            [main-caption]="'This is some text'"
            [is-active]="true"
            [use-button]="true">
</walkthrough>

**Comment by bobo04020802** [comment]
@Altaba77 i found how to solution this question ，if ionic3 lazy load， this plugin is not support 。thanks you~~

**Comment by Altaba77** [comment]
Hello,

After testing it, it seems that this library does not work with lazy loading, thank you for noting it. I will work on this point when I have time.

Regards,
