### ISSUE TITLE
Ionic 3 with Angular 5

### ISSUE THREAD

**Issue by ansarikhurshid786** [Altaba77/ngx-walkthrough#6]
HI, 
I am using integrating with ionic 3 with angular 5. It is working fine but when i m compiling with production(magnification) it is not working.  

it is not working i am giving command as below: 
ionic cordova build android  --aot
or
ionic cordova build android --prod

**Comment by Altaba77** [comment]
Hello,

Are you using Lazy Loading in your Ionic project ?

**Comment by ansarikhurshid786** [comment]
No I am not using lazy loading.

**Comment by ansarikhurshid786** [comment]
I am getting error when I am running app with --aot flag

Error : 
"Error: ./node_modules/ngx-walkthrough/walkthrough.ngfactory.js Module not found: Error: Can't resolve 'walkthrough'

**Comment by SonuSahoo** [comment]
Hi I am using the same ngx-walkthrough but while using it in homepage after login its giving me error can somebody help me.
